// Code generated by MockGen. DO NOT EDIT.
// Source: ../Logger.go

// Package mock_pkg is a generated GoMock package.
package infraestructure

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// PrintLine mocks base method.
func (m *MockLogger) PrintLine(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintLine", message)
}

// PrintLine indicates an expected call of PrintLine.
func (mr *MockLoggerMockRecorder) PrintLine(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintLine", reflect.TypeOf((*MockLogger)(nil).PrintLine), message)
}
